update

diff --git a/.github/workflows/pipleline.yml b/.github/workflows/pipleline.yml
--- a/.github/workflows/pipleline.yml
+++ b/.github/workflows/pipleline.yml
@@ -69,9 +69,18 @@ jobs:
           cd kivra-clone-backend
           npm test
 
-      - name: Upload Playwright report (if tests are run)
-        if: always()
+      - name: Check if Playwright report exists
+        run: |
+          if [ -d "playwright-report" ]; then
+            echo "Playwright report exists"
+          else
+            echo "Playwright report does not exist"
+            exit 1
+          fi
+
+      - name: Upload Playwright report
+        if: always()  # Upload the report even if tests fail
         uses: actions/upload-artifact@v2
         with:
           name: playwright-report
-          path: playwright-report/**
+          path: playwright-report/**  # Ensure that this path is correct and the report exists
